Repository googleapis/nodejs-security-center, pull requests merged in 2019-04, with the labels that each got.

#78 docs: improve the jsdoc documentation
  protos/google/cloud/securitycenter/v1/securitycenter_service.proto
  src/v1/doc/google/cloud/securitycenter/v1/doc_securitycenter_service.js
  src/v1/security_center_client.js
  synth.metadata
Labels: cla: yes

#80 refactor: use execSync for tests
  samples/package.json
  samples/system-test/quickstart.test.js
Labels: automerge, cla: yes

#81 refactor: wrap execSync with encoding: utf-8
  samples/system-test/quickstart.test.js
Labels: cla: yes

#83 chore: update proto metadata
  protos/google/cloud/securitycenter/v1/securitycenter_service.proto
  synth.metadata
Labels: cla: yes

#84 feat: asset path template & matchers
  src/v1/security_center_client.js
  synth.metadata
Labels: cla: yes

#86 chore: update code formatting
  protos/google/cloud/securitycenter/v1/asset.proto
  protos/google/cloud/securitycenter/v1/finding.proto
  protos/google/cloud/securitycenter/v1/organization_settings.proto
  protos/google/cloud/securitycenter/v1/security_marks.proto
  protos/google/cloud/securitycenter/v1/source.proto
  synth.metadata
Labels: :rotating_light:, automerge, cla: yes

#89 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes

#88 refactor: update generated sources
  protos/google/cloud/securitycenter/v1/securitycenter_service.proto
  src/v1/doc/google/cloud/securitycenter/v1/doc_securitycenter_service.js
  src/v1/doc/google/protobuf/doc_any.js
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/security_center_client.js
  src/v1beta1/doc/google/protobuf/doc_any.js
  src/v1beta1/doc/google/protobuf/doc_field_mask.js
  src/v1beta1/doc/google/protobuf/doc_timestamp.js
  src/v1beta1/security_center_client.js
  synth.metadata
Labels: cla: yes

#87 docs: use repo-metadata to generate README
  .cloud-repo-tools.json
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/quickstart.js
  samples/system-test/quickstart.test.js
  synth.metadata
Labels: automerge, cla: yes
