Repository googleapis/nodejs-security-center, pull requests merged in 2019-05, with the labels that each got.

#94 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#93 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#95 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#97 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#98 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#99 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#103 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#104 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#108 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#106 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#110 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#105 fix: drop dependency on lodash.merge
  package.json
  protos/google/cloud/securitycenter/v1/run_asset_discovery_response.proto
  src/v1/doc/google/type/doc_expr.js
  src/v1/security_center_client.js
  src/v1beta1/doc/google/type/doc_expr.js
  src/v1beta1/security_center_client.js
  synth.metadata
Labels: cla: yes
