Repository googleapis/nodejs-security-center, pull requests merged in 2019-07, with the labels that each got.

#119 fix: import run_asset_discovery_response.proto
  protos/google/cloud/securitycenter/v1/securitycenter_service.proto
  samples/.eslintrc.yml
  src/index.js
  src/v1/doc/google/iam/v1/doc_iam_policy.js
  src/v1/doc/google/iam/v1/doc_options.js
  src/v1/security_center_client.js
  src/v1beta1/doc/google/iam/v1/doc_iam_policy.js
  src/v1beta1/doc/google/iam/v1/doc_options.js
  src/v1beta1/security_center_client.js
  synth.metadata
  synth.py
Labels: cla: yes

#120 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#82 docs(samples): add a comprehensive set of samples
  .kokoro/samples-test.sh
  samples/package.json
  samples/system-test/v1/assetSecurityMarks.test.js
  samples/system-test/v1/findings.test.js
  samples/system-test/v1/listAllAssets.test.js
  samples/system-test/v1/listAssetsAndChanges.test.js
  samples/system-test/v1/listAssetsAtTime.test.js
  samples/system-test/v1/listFilteredAssets.test.js
  samples/system-test/v1/orgSettings.test.js
  samples/v1/addDeleteSecurityMarks.js
  samples/v1/addFindingSecurityMarks.js
  samples/v1/addSecurityMarks.js
  samples/v1/createFinding.js
  samples/v1/createFindingSourceProperties.js
  samples/v1/createSource.js
  samples/v1/deleteSecurityMarks.js
  samples/v1/enableAssetDiscovery.js
  samples/v1/getOrganizationSettings.js
  samples/v1/getSource.js
  samples/v1/getSourceIam.js
  samples/v1/listAllAssets.js
  samples/v1/listAllFindings.js
  samples/v1/listAllSources.js
  samples/v1/listAssetsAndChanges.js
  samples/v1/listAssetsAtTime.js
  samples/v1/listAssetsWithSecurityMarks.js
  samples/v1/listFilteredAssets.js
  samples/v1/listFilteredFindings.js
  samples/v1/listFindingsAtTime.js
  samples/v1/listFindingsWithSecurityMarks.js
  samples/v1/setFindingState.js
  samples/v1/setSourceIam.js
  samples/v1/testIam.js
  samples/v1/updateFindingSourceProperties.js
  samples/v1/updateSource.js
  synth.py
Labels: :rotating_light:, cla: yes

#121 docs: add reference in jsdoc header
  src/index.js
  synth.metadata
Labels: cla: yes

#122 feat!: adds findingSecurityMarksPathTemplate
  src/index.js
  src/v1beta1/security_center_client.js
  synth.metadata
  synth.py
  test/gapic-v1beta1.js
Labels: cla: yes

#124 docs: update jsdoc to make datetime usage more clear
  protos/google/cloud/securitycenter/v1/securitycenter_service.proto
  src/v1/doc/google/cloud/securitycenter/v1/doc_securitycenter_service.js
  src/v1/security_center_client.js
  synth.metadata
Labels: cla: yes

#126 fix(deps): remove unused dependency
  package.json
Labels: cla: yes

#123 chore: release 2.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#129 docs: use the jsdoc-fresh theme
  .jsdoc.js
  package.json
Labels: cla: yes

#132 docs: document apiEndpoint over servicePath
  src/v1/security_center_client.js
  src/v1beta1/security_center_client.js
Labels: cla: yes
