Repository googleapis/nodejs-security-center, pull requests merged in 2020-11, with the labels that each got.

#335 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#336 build: export type v1.SecurityCenterClient
  src/index.ts
  synth.metadata
Labels: api: securitycenter, cla: yes, context: none

#337 fix: do not modify options object, use defaultScopes
  package.json
  src/v1/security_center_client.ts
  src/v1beta1/security_center_client.ts
  src/v1p1beta1/security_center_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: securitycenter, automerge, cla: yes

#344 fix: check for fetch on window
  protos/protos.json
  src/v1/security_center_client.ts
  src/v1beta1/security_center_client.ts
  src/v1p1beta1/security_center_client.ts
  synth.metadata
Labels: api: securitycenter, cla: yes, context: partial

#346 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full
