Repository googleapis/nodejs-security-center, pull requests merged in 2020-07, with the labels that each got.

#294 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#295 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#298 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#300 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#288 docs: Add filter field libary sample for UpdateNotificationConfig
  samples/v1/updateNotificationConfig.js
Labels: cla: yes

#302 fix: correct securitycenter grpc_service_configs, add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  src/v1/security_center_client_config.json
  src/v1beta1/security_center_client_config.json
  src/v1p1beta1/security_center_client_config.json
  synth.metadata
Labels: cla: yes, context: partial

#303 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#305 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#307 fix: add resource config to v1beta1
  protos/google/cloud/securitycenter/v1beta1/asset.proto
  protos/google/cloud/securitycenter/v1beta1/finding.proto
  protos/google/cloud/securitycenter/v1beta1/organization_settings.proto
  protos/google/cloud/securitycenter/v1beta1/run_asset_discovery_response.proto
  protos/google/cloud/securitycenter/v1beta1/security_marks.proto
  protos/google/cloud/securitycenter/v1beta1/securitycenter_service.proto
  protos/google/cloud/securitycenter/v1beta1/source.proto
  protos/protos.json
  src/v1beta1/security_center_client.ts
  synth.metadata
  test/gapic_security_center_v1beta1.ts
Labels: cla: yes, context: full

#306 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#308 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#312 build: config for new reference docs
  .kokoro/release/docs-devsite.cfg
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial
